version: "3.9"

services:
  backend:
    build: .
    container_name: ecopack_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../src:/app/src

  db:
    image: postgres:15
    container_name: ecopack_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecopackai_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecopack_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ecopack.ai
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

volumes:
  pg_data:
