"""Initial migration

Revision ID: 7ec70a8ccf05
Revises: 
Create Date: 2026-01-20 12:24:37.749134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec70a8ccf05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=False),
    sa.Column('strength_mpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('biodegradability_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('co2_emission_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recyclability_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('industry_use_case', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('product_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fragility_index', sa.Integer(), nullable=True),
    sa.Column('shipping_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('recommendation_logs',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('recommended_material_id', sa.Integer(), nullable=True),
    sa.Column('cost_prediction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('co2_prediction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('material_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_material_id'], ['materials.material_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('rec_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_logs')
    op.drop_table('products')
    op.drop_table('materials')
    # ### end Alembic commands ###
