"""Initial material table

Revision ID: bb24cbfa45cd
Revises: 
Create Date: 2026-01-07 05:09:14.687154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb24cbfa45cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materials_raw')
    op.drop_table('products')
    op.drop_table('recommendation_logs')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('material_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('co2_emission_score')
        batch_op.drop_column('indusrty_use_case')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('indusrty_use_case', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co2_emission_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('material_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('id')

    op.create_table('recommendation_logs',
    sa.Column('rec_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommended_material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_prediction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('co2_prediction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('material_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('recommendation_logs_product_id_fkey')),
    sa.PrimaryKeyConstraint('rec_id', name=op.f('recommendation_logs_pkey'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('product_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fragility_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipping_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name=op.f('products_pkey'))
    )
    op.create_table('materials_raw',
    sa.Column('material_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strength_mpa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight_capacity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('co2_emission_score', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biodegradability_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recyclability_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cost_per_kg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('indusrty_use_case', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
